apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment-crmode
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-deployment-crmode
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr-deployment-crmode
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.5.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.1.20.5",
            "--bigip-partition=OpenShift",
            "--pool-member-type=cluster",
            "--insecure=true",
            "--manage-routes=true",
            "--log-level=DEBUG",
            "--log-as3-response=true",
            "--route-vserver-addr=10.1.10.100",
            "--openshift-sdn-name=/Common/openshift_vxlan",
            "--override-as3-declaration=default/f5-as3-override",
            "--hubmode=true",
            "--namespace-label=use_cis=true"
            ]
      serviceAccountName: bigip-ctlr
