---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    cis.f5.com/as3-app: my-app
    cis.f5.com/as3-pool: tls-backend
    cis.f5.com/as3-tenant: cm-mode
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
