kind: ConfigMap
apiVersion: v1
metadata:
  name: tls-passthrough
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "cm-mode": {
                "class": "Tenant",
                "my-app": {
                    "class": "Application",
                    "template": "generic",
                    "tls-passthrough": {
                        "class": "Service_TCP",
                        "remark": "n1 namespace",
                        "virtualAddresses": [
                            "10.1.10.200"
                        ],
                        "virtualPort": 443,
                        "pool": "tls-backend"
                    },
                    "tls-backend": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 8443,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
