apiVersion: v1
kind: ConfigMap
metadata:
  name: cis-extended-spec-override
  namespace: app
  labels:
    f5nr: "true"
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: app
      vserverAddr: 10.1.10.200
      vserverName: override-vs
