apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: blue
spec: {}
status: {}
---
apiVersion: v1
data:
  index.html: |
    blue
kind: ConfigMap
metadata:
  name: nginx-blue
  namespace: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-blue
  name: nginx-blue
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-blue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-blue
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-conf
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-blue
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-blue
  name: nginx-blue-ipv6
  namespace: blue
spec:
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-blue
  type: NodePort
