apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: blue-vs
  namespace: blue
  labels:
    f5cr: "true"
spec:
  host: blue.example.com
  virtualServerAddress: "fdbd:bdbd:bdbd:20:0:0:0:100"
  pools:
  - path: /
    service: nginx-blue-ipv6
    servicePort: 8080
    monitor:
      type: http
      interval: 20
      recv: ""
      send: "GET /e HTTP/1.1\r\n\r\n"
      timeout: 10
  serviceAddress:
  - icmpEcho: "enable"
    arpEnabled: true
    routeAdvertisement: "all"
    spanningEnabled: false
