apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  labels:
    f5cr: "true"
spec:
  domainName: crmode.example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: crmode.example.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/bigip-10-1-1-5
    monitor:
      type: http
      send: "GET /"
      recv: ""
      interval: 10
      timeout: 10