apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: ipam-vs
  labels:
    f5cr: "true"
spec:
  ipamLabel: Default
  host: ipam.example.com
  pools:
  - path: /
    service: nginx
    servicePort: 80
