apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: multipath-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.120"
  host: multipath.example.com
  pools:
  - path: /nginx
    service: nginx
    servicePort: 80
    rewrite: /
  - path: /f5
    service: f5-hello-world
    servicePort: 8080
    rewrite: /
