kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration-a1
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
    hubMode: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210",
            "label": "http",
            "remark": "A1 Template",
            "Tenant1": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "a1_80_vs_n1": {
                        "class": "Service_HTTP",
                        "remark": "n1 namespace",
                        "virtualAddresses": [
                            "10.1.10.51"
                        ],
                        "pool": "web_pool_n1",
                        "iRules": [
                            "choose_pool"
                        ]
                    },
                    "web_pool_n1": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "choose_pool": {
                      "class": "iRule",
                      "remark": "choose private pool based on IP",
                      "iRule": "when CLIENT_ACCEPTED {\nif {[IP::client_addr] starts_with \"10.\"} {\n log local0. \"log\"\n }\n}"
                    }
                }
            }
        }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration-a2
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
    hubMode: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210",
            "label": "http",
            "remark": "A1 Template",
            "Tenant2": {
                "class": "Tenant",
                "A2": {
                    "class": "Application",
                    "template": "generic",
                    "a1_80_vs_n2": {
                        "class": "Service_HTTP",
                        "remark": "n2 namespace",
                        "virtualAddresses": [
                            "10.1.10.52"
                        ],
                        "pool": "web_pool_n2"
                    },
                    "web_pool_n2": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
